### ISSUE TITLE
We need to provide grid.xml download option for each shake

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe-django#100]
In the row for each shake and in the popup, we should let the user grab the `grid.xml` (perhaps delivered as <shakeid>.xml so that we can support this kind of work flow:
- go to site and see a new shake
- grab the grid.xml
- use the grid convertor in inasafe to make it into a tif
- run an EQ on teh data using e.g. OSM buildings

**Comment by timlinux** [comment]
cc @Charlotte-Morgan

**Comment by Charlotte-Morgan** [comment]
this sounds fantastic

**Comment by lucernae** [comment]
added to to-do-list :).
Needs to develop this in tandem with inasafe realtime that will provide the xml.

**Comment by gubuntu** [comment]
done ages ago
