### ISSUE TITLE
Inasafe-django Backup Plan

### ISSUE THREAD

**Issue by lucernae** [inasafe/inasafe-django#115]
By using sftp-backup, we can create a hanoi-fashioned backup plan to remote sftp server.
# How SFTP Backup works

SFTP-backup is a backup service in docker. To use it, one must provides remote SFTP Credentials, SFTP directory to put the backup into, the target directory to backup (as a docker volume) and a local backup folder (as a docker volume).

This service will try to make a compressed tar ball (tar.gz) of the target directory.
The compressed file will be stored into a local backup folder and then pushed to
a remote sftp directory. Each archive is given a unique filename based on the day
the archive is created, and will be put into a nicely ordered structure of Year/Month
folder. So, in the local and remote folder, there can be several backup file to be kept.

To control how many backup file to keep. We can specify 3 environment variable into
the docker container. There are yearly, monthly, and daily variable. Each variable
is used as a limit of how many latest backup to keep. Example, 7 daily backup means
the service will try to keep 7 most recent daily backup, and 12 monthly backup means
the service will try to keep 12 most recent monthly backup (created at 1st date each 
month). The same applies to yearly backup.

There are also command to push and pull all backups. Pull commands mean the 
service will try to pull all the backups being kept in remote SFTP directory in to local
backup folder. Push command do otherwise. The command will overwrites existing
backup if the name is conflicted.

In inasafe django, two folder needs to be backed up. The latest dump, and media folder.
The media folder is quite big, so maybe we want to reduce the backup frequency.

**Comment by gubuntu** [comment]
@lucernae haven't your recently resolved this in the latest orchestration?

**Comment by gubuntu** [comment]
This issue was moved to inasafe/docker-realtime-orchestration#70
