### ISSUE TITLE
Test and handle concurrency problem when posting multiple reports

### ISSUE THREAD

**Issue by lucernae** [inasafe/inasafe-django#118]
# Problem

Sometimes, the server can't handle when multiple reports with the same shake id and language id is posted at the same time.
# Current situation
## Original status

GET requests handler is trying to make sure that only one particular reports is saved. But the method is not atomic, so in an unlikely event, it maybe still occurs.
## Update 18 November 2015

The problem occured again. So, we are trying to put database level lock by using django model's `unique_together` Meta options, which should be implemented in low level by the db backend. If multiple post requests do occured, we can reject one of them, and let the request update it again via put request at a later time.

**Comment by gubuntu** [comment]
close @lucernae ?

**Comment by gubuntu** [comment]
no longer a problem - stale.
