### ISSUE TITLE
Create REST API for flood realtime

### ISSUE THREAD

**Issue by lucernae** [inasafe/inasafe-django#120]
The REST API also used to communicate with Realtime Processor
- Post/Put Flood events
  - Flood Event
  - Flood geometries (retrieved from shp layer)
  - Flood Reports/Map PDF
- Get List of Flood Events
- Get Geojson of flood events impact layer (to display it in map)

**Comment by gubuntu** [comment]
http://realtime.inasafe.org/realtime/api/v1/
