### ISSUE TITLE
Use BMKG Shake list to confirm Realtime Shake map push

### ISSUE THREAD

**Issue by lucernae** [inasafe/inasafe-django#123]
BMKG now have a list of shakes in their website.

[Shake list](http://www.bmkg.go.id/BMKG_Pusat/Gempabumi_-_Tsunami/Gempabumi/Gempabumi_Dirasakan.bmkg)

But sometimes InaSAFE realtime is more actual than their list (weird).
We can still check the shake list to confirm that we're not missing any shakemap
# Update

It turns out, they have two kind of lists. The second one is for about the shakemap with magnitude more than 5. [Shake list more than 5 MMI](http://www.bmkg.go.id/BMKG_Pusat/Gempabumi_-_Tsunami/Gempabumi/Gempabumi_Terkini.bmkg). So we should check from both

**Comment by gubuntu** [comment]
above links are no longer valid

guess there would be a list of raw / 'five-minute' shakemaps and a list of 'data-informed chakemaps form the other department. 

It would still be useful to compare and ensure we aren't missing any

**Comment by gubuntu** [comment]
This issue was moved to inasafe/inasafe-realtime#122
