### ISSUE TITLE
Fix bugs appearing in sentry.

### ISSUE THREAD

**Issue by lucernae** [inasafe/inasafe-django#128]
There are 2 bugs:
1. Missing kelurahan boundary and not saved. Perhaps we should save this.
2. Malformed data of petajakarta state value sometimes empty, so should be normalized as not flooded.

**Comment by gubuntu** [comment]
@lucernae close?

**Comment by gubuntu** [comment]
fixed a while ago

**Comment by lucernae** [comment]
It was fixed when Petajakarta migrated to PetaBencana v2.
