### ISSUE TITLE
add 'About' pages to describe each realtime product

### ISSUE THREAD

**Issue by gubuntu** [inasafe/inasafe-django#187]
_From @gubuntu on March 2, 2017 5:50_

@timlinux please expand (taken from your meeting with Charlotte on 1 March)

_Copied from original issue: inasafe/inasafe-realtime#70_

**Comment by gubuntu** [comment]
_From @timlinux on March 2, 2017 20:9_

I think it should explain the funders, partners, data sources, update frequency, workflows, provide contact points for reporting issues etc. Please refer to InaSAFE.org for the boilerplate project description stuff, resources folder in InaSAFE codebase to logos etc. and Rizky's brains for the implementation details. I also forwarded you a bunch of realtime diagrams - the originals are in the omnigraffle doc in InaSAFE code tree - it would be good to provide simple diagrammatic representations of each hazard workflow (currently EQ, Flood, Ash).

**Comment by gubuntu** [comment]
_From @Charlotte-Morgan on March 17, 2017 7:0_

I think we need an about page for each mealtime service - ie earthquake, flood and volcanic ash. These need to describe the data used in the analyses, analysis methods, limitations and assumptions. These will be very different for each product.

**Comment by gubuntu** [comment]
_From @Charlotte-Morgan on March 17, 2017 7:1_

I have asked @ivanbusthomi to start work on these 'metadata' about pages

**Comment by gubuntu** [comment]
_From @Charlotte-Morgan on April 13, 2017 4:22_

Discussed again today re content required and why.
Content:
Data
Analysis
methods
download data formats
api links 

Action: @ivanbusthomi to prepare content with help from @samnawi 
Action: @gubuntu to prepare place holder for this content on website
Time required : before 26th April for DM day

**Comment by gubuntu** [comment]
@lucernae to add Flatpages for Django to the Realtime site so @ivanbusthomi and @gubuntu can edit these pages directly

**Comment by gubuntu** [comment]
_From @ivanbusthomi on April 24, 2017 4:35_

WIP [Shared Google Docs]() for realtime about pages.
Edit: link is removed.

**Comment by gubuntu** [comment]
_From @lucernae on May 16, 2017 11:5_

@gubuntu The admin pages is in realtime.inasafe.org/admin
If the About pages you created has title 'About' It will show up automatically in the second navbar (after Indicator)

**Comment by gubuntu** [comment]
Thanks @lucernae. I've got one working. I guess we can put then all on one page. How would you like it @ivanbusthomi? 

Please add TinyMCE or similar. Easier than asking @ivanbusthomi to paste html?

**Comment by gubuntu** [comment]
_From @ivanbusthomi on May 17, 2017 4:42_

@gubuntu and @lucernae
Yeah, I think all in one page is fine. we can just add some sections for specific realtime information.

**Comment by gubuntu** [comment]
_From @Charlotte-Morgan on June 19, 2017 4:4_

hi @lucernae  - can you please give an update on this? When will it be ready for me to start adding content?

**Comment by gubuntu** [comment]
@lucernae please deploy this to production so it can be used

**Comment by gubuntu** [comment]
_From @lucernae on June 20, 2017 9:56_

I updated just the tiny mce. But since now it uses a different table, @ivanbusthomi you need to create a new about page.
You can navigate to realtime.inasafe.org/admin once you're logged in as admin

**Comment by gubuntu** [comment]
_From @Charlotte-Morgan on June 20, 2017 11:23_

So we should update text before it goes to production?
Pls give me admin access so I can work on the new content. Thanks

**Comment by gubuntu** [comment]
_From @Charlotte-Morgan on June 21, 2017 6:25_

hi @lucernae I am not seeing the about page now on either staging or production. Is this what you expect?

**Comment by gubuntu** [comment]
@Charlotte-Morgan, @lucernae asked @ivanbusthomi above to create the about page in admin,

**Comment by gubuntu** [comment]
_From @Charlotte-Morgan on June 21, 2017 7:21_

Hi @gubuntu and @lucernae  - I see the comment for @ivanbusthomi but he is on leave for 2 weeks so what this means is you have deployed a change that is a regression. I think it would be better you tell us staging is ready for us to enter info as admin and then we deploy once its populated.
Also, Ivan will not have final approval on content so we need to coordinate this better between our teams if possible.

**Comment by gubuntu** [comment]
_From @Charlotte-Morgan on June 21, 2017 7:33_

@ivanbusthomi  - I think we still have a lot of work to do on the content for the 'about' pages in your shared document. Do you have any more progress on this?

**Comment by gubuntu** [comment]
I didn't realise Ivan was away. I've created an about page and populated it with the content directly from the Google Doc. 

Edit it here: http://realtime.inasafe.org/admin/realtime/coreflatpage/ 

Styles can be changed to match the rest of the site (comment @lucernae)

@lucernae just wondering why you replaced 'flat pages' with 'core flat pages'?

**Comment by gubuntu** [comment]
_From @Charlotte-Morgan on June 21, 2017 9:14_

Hi @gubuntu can you please remove that content - it is not suitable to include on the public page.

**Comment by gubuntu** [comment]
_From @lucernae on June 21, 2017 9:16_

> @lucernae just wondering why you replaced 'flat pages' with 'core flat pages'?

 I had to inherit the table to include django tiny mce and add customization for the field. The name is to indicate that it is a different table.

**Comment by gubuntu** [comment]
_From @lucernae on June 22, 2017 1:45_

@Charlotte-Morgan @timlinux @gubuntu @ivanbusthomi 
I sent emails with the secured googledocs containing the credentials yesterday.

> Hi @gubuntu can you please remove that content - it is not suitable to include on the public page.

I deleted it just now. User with credentials also can delete it. First access django admin page (I put the relative url in the googledocs for security reasons), then select Core flat pages models, and select the content you want to delete, then delete it.

> Styles can be changed to match the rest of the site (comment @lucernae)

Styles will match if you put the correct bootstrap css or any css rules the site supports. Perhaps we need to give @ivanbusthomi a mini training about bootstrap for advanced pretty customizations 😄 .

> what this means is you have deployed a change that is a regression.

The code is the same, and the flatpage content can be put manually by users with credentials either in staging or production. What I suggests is to use staging first to see how it looks, then copy the same content to production.

If any of you want a specific username for admin access, let me know the username. We never had admin user before.

**Comment by gubuntu** [comment]
_From @Charlotte-Morgan on June 23, 2017 4:50_

hi @lucernae 
I am having trouble understanding the instructions you have provided. Is it possible you can do a quick walk through with me so I can see what I am supposed to be doing?

**Comment by gubuntu** [comment]
_From @Charlotte-Morgan on June 30, 2017 2:14_

@lucernae thanks for your lessons. 
I see the about pages have been published again on the public website but with the 'google doc' content which I have mentioned many times should not be used. Can this please be removed?
I am happy for the draft content and styling that @gubuntu prepared to appear on staging so we have a framework to build on with the relevant content.
cc @timlinux

**Comment by gubuntu** [comment]
Just to clarify the way forward

- @ivanbusthomi continue improving the About content in the Google Doc. 
- I will transfer the Google Doc content to http://staging.realtime.inasafe.org/realtime/pages/about/ (again) and format it unless @lucernae can restore my previous attempt (not to production but to staging).
- once transferred, no more work must be done on the Google Doc (It can be deleted then)
- then all further work to happen on the staging about page(s)
- once approved by @Charlotte-Morgan the pages can be copied over to production.

**Comment by gubuntu** [comment]
_From @Charlotte-Morgan on July 12, 2017 22:58_

> Just to clarify the way forward

>@ivanbusthomi continue improving the About content in the Google Doc.
 I will transfer the Google Doc content to http://staging.realtime.inasafe.org/realtime/pages/about/ 
 (again) and format it unless @lucernae can restore my previous attempt (not to production but to staging).
once transferred, no more work must be done on the Google Doc (It can be deleted then)
then all further work to happen on the staging about page(s)
once approved by @Charlotte-Morgan the pages can be copied over to production.

hi @gubuntu that is not my recollection or what we are working on. 
This is what I was thinking we had agreed. 

- @lucernae to restore the page he deleted from staging  when he gave me the demo - ie get back the page with @gubuntu formating.
- @ivanbusthomi and I are working on content for about pages. This is in a google doc but only shared with DMI - ie DMI will finalise the content but no formatting
- @ivanbusthomi will then transfer approved content to staging. DMI may need some assistance with formatting etc but will try to do this.
- once the page/pages are finished on staging (content and layout etc) they can be copied over to production. @lucernae will be asked to help with this.
- we will also want to include translated pages eventually.

Timing - this is a high priority and we really want to have this content live on production before the August training.

**Comment by gubuntu** [comment]
_From @Charlotte-Morgan on August 3, 2017 5:25_

Update from @ivanbusthomi and me. We have text ready for earthquake and expect to have text ready for flood next week.

**Comment by gubuntu** [comment]
we just need ash then we can close?

**Comment by Charlotte-Morgan** [comment]
@gubuntu - yes we need the  ash text but we also need the about pages be on production not just staging.

**Comment by gubuntu** [comment]
@lucernae please deploy the updated menu structure to production and copy Flood and EQ About content to the production pages

and create and empty page with menu item in staging

**Comment by lucernae** [comment]
I will update it after situational managers training

**Comment by lucernae** [comment]
@Charlotte-Morgan @gubuntu Changes are now live on Production (I copied the flat page content from staging).
The flatpages haven't supported multi language in the code yet (we have to manually add content for other language later)

**Comment by gubuntu** [comment]
done and deployed
