### ISSUE TITLE
Realtime earthquake translation in Bahasa Indonesia

### ISSUE THREAD

**Issue by gubuntu** [inasafe/inasafe-django#190]
_From @christodewit on January 30, 2017 11:32_

Problem

Similar issue with InaSAFE Realtime flood translation (#3291), currently InaSAFE Realtime Earthquake in Bahasa Indonesia is not 100% translated yet.

See original ticket at https://github.com/inasafe/inasafe/issues/3714 for further discussion.

_Copied from original issue: inasafe/inasafe-realtime#36_

**Comment by gubuntu** [comment]
_From @lucernae on February 6, 2017 17:24_

linked with #50

**Comment by gubuntu** [comment]
can we close @lucernae

**Comment by lucernae** [comment]
The resource is uploaded on transifex and will be updated in case new strings comes out.
