### ISSUE TITLE
Realtime flood translation in Bahasa Indonesia

### ISSUE THREAD

**Issue by gubuntu** [inasafe/inasafe-django#191]
_From @christodewit on January 31, 2017 6:43_

Problem
We have a good real time monitoring [http://realtime.inasafe.org/] , but there are some problems if we want to see it in Bahasa Indonesia mode. When a new user going to open the real time and they just only know in Bahasa, they will always want to translate it, from English to Bahasa Indonesia. But, in a current release when I want to translate the real time into Bahasa is not translate yet. From the menu until the data flood query most of them not translate yet.

See original ticket at https://github.com/inasafe/inasafe/issues/3291 for further discussion.

_Copied from original issue: inasafe/inasafe-realtime#50_

**Comment by gubuntu** [comment]
_From @Charlotte-Morgan on July 13, 2017 6:33_

@lucernae to implement transifex and DMI to help with translation.

**Comment by gubuntu** [comment]
_From @lucernae on July 21, 2017 3:42_

Linked with #36 

CC @Charlotte-Morgan @ivanbusthomi @felix-yew 

I've prepared another string resource in our Transifex resource here:
https://www.transifex.com/inasafe/inasafe-code/content/
There are two new resources called InaSAFE Realtime and InaSAFE Django. DMI can help translate the strings (not many). The workflow will be similar with InaSAFE codebase. You can translate in transifex, then after it is finished, ping me to compile the strings into the code. Then if there's new strings to translate, I will update both the resources.

Note:
InaSAFE Realtime: Resource related with the report (Shake report, Flood Report, Ash Report)
InaSAFE Django: Resource related with the web user interface/web page.

**Comment by gubuntu** [comment]
can we close this @lucernae?

**Comment by Charlotte-Morgan** [comment]
How will the about pages be translated?

**Comment by lucernae** [comment]
The about pages needs to be translated by the person who put the core flatpage and it should be marked with the correct language code.
