### ISSUE TITLE
Flood table heading should be clearer

### ISSUE THREAD

**Issue by gubuntu** [inasafe/inasafe-django#213]
_From @timlinux on February 10, 2017 7:9_

![screen shot 2017-02-10 at 9 05 51 am](https://cloud.githubusercontent.com/assets/178003/22817490/46341ad2-ef70-11e6-9557-862bbb1f3b7f.png)

"RW Flooded" should rather be "# Flooded RWs"

_Copied from original issue: inasafe/inasafe-realtime#61_

**Comment by gubuntu** [comment]
_From @Charlotte-Morgan on December 21, 2017 4:30_

@myarjunar  - is this something you can tweak?

**Comment by lucernae** [comment]
@myarjunar I think you can easily tweak this.
