### ISSUE TITLE
Papercuts for version 1

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe-django#75]
These are mainly GUI papercuts:

**General**
- [x] favicon needs to be swapped the monochrome black one
- [x] Fonts should be san seriff - see css on http://blogtest.inasafe.org
- [x] top level menu should be standard items as per top level menu in http://blogtest.inasafe.org
- [x] We can ditch the about view / menu items - we will get it from the parent site
- [x] We need to incorporate the opening paragraph from http://realtime.inasafe.org/ as a paragraph above the map
- [x] We should add BNPB and BMKG logos under the table

**Map**
- [x] Remove shadows from icons on map
- [x] Select area button - remove text and use tooltip rather to explain its use
- [x] Replace 'Map' in title with text explaining what is being shown e.g. 'Earthquake events between magnitude 5 and 7 over the period 1 July 2014 and 1 July 2015'
- [x] Switch the map tiles used to the one used on http://watchkeeper.kartoza.com/ and add HOT OSM tiles as a secondary option
- [x] Add 'Zoom all' button (use `glyphicon glyphicon-globe`) - or get Maria to make a more appropriate one.

**Table Box**
- [x] Table - replace `Show` with magnifying glass bootstrap glyph (`glyphicon glyphicon-search`)
- [x] Table - replace `Report` with Document icon (bootstrap glyph `glyphicon glyphicon-file`)
- [x] Open report buttons (report and map popup) - pop up pdf in a new tab, don't replace ccurrent page url
- [x] Table - add `Download` with download icon (bootstrap glyph `glyphicon glyphicon-download`) which will download the PDF directly without opening in new tab
- [x] Table - add padding between icons
- [x] Please reformat times to look like: `2014-02-11 at 02h08:07`
- Remove colon (`:`) after `Search` and `Show` labels

**Filter Box**
- [x] Filter box - replace button for clear with icon: `glyphicon glyphicon-erase`
- [x] Filter box - replace button for apply with icon: `glyphicon glyphicon-ok`
- [x] Filter box - move clear and ok button to right of filter boxes to reduce vertical space of filter box

**Comment by timlinux** [comment]
@Charlotte-Morgan cc FYI, please add any papercuts you see to my list above - staging site is visible at http://staging.users.inasafe.org/

**Comment by lucernae** [comment]
Several notes:
General
- Font: I'm using Ubuntu family font just like in the blog css. Are you sure I need to change it to sans serif? (It already doesn't have serif)
- Top level menu: You mean the whole blog menu like 'For users', 'For contributors'? If so, where should we put the realtime and usermap menu?

**Comment by Charlotte-Morgan** [comment]
Hi - a few extra paper cuts & observations from me that might need more work
I have only looked at Realtime - not the Usermap (which only has one user :( )

**General**
- [ ] the top menu offers English even when I am already in English - should it offer Indonesian?
- [ ] how does the user get back to the staging page from inside the realtime page

**Map**
- [ ] select area button - is there a better icon to use (the current one looks like some thing to do with editing)
- [ ] zoom all button - needs a better icon. The current one is very small
- [ ] make all the icons the same size - like the layers icon

**Filters**
- [ ] the filter and clear filter icons are active even if no filter is set
- [ ] the filter date lets me enter text but does not return a value; the date format required may not be logical to all users. 
- [ ] the magnitude filter lets me enter stupid values ie 43 and 55 and it runs
- [ ] please reconsider allowing free text in the filters - maybe just use the calendar and drop downs to force the correct format for filters

**Table Box**
- [ ] Action Icon - maybe change the "show" label to say "zoom"
- [ ] not clear how to close a report after it has been opened
- [ ] reduce the default table size to 20 records
- [ ] Sort events from most recent at top to oldest at bottom - default setting

**Bragging**
- [ ] Partners - remove the fullstop after (BNPB)
- [ ] should we mention and provide a link to InAWARE?

**Comment by lucernae** [comment]
Several notes:

>  the top menu offers English even when I am already in English - should it offer Indonesian?
Yes it should, but not currently

>  how does the user get back to the staging page from inside the realtime page
We discard the front page. The user will navigate using the navbar which should be the same with blogtest.inasafe.org

>  select area button - is there a better icon to use (the current one looks like some thing to do with editing)
> zoom all button - needs a better icon. The current one is very small

We'll have to ask maria for this.

> the filter date lets me enter text but does not return a value; the date format required may not be logical to all users.

> please reconsider allowing free text in the filters - maybe just use the calendar and drop downs to force the correct format for filters

We're supposed to be entering it using calendar widget. Perhaps I will disable the text, but still allow it to be visible, so the user can know what date s/he just entered.

> the magnitude filter lets me enter stupid values ie 43 and 55 and it runs
Ok, I haven't put validation. I assume the value will be 1 to 10 inclusive?

> not clear how to close a report after it has been opened

The report shows up in a new tab, right? I thought it should be natural to close it using standard close button in browser tab. Maybe I misunderstood the problem though, could you explain more @Charlotte-Morgan ?

>  reduce the default table size to 20 records

Contradictory with what @timlinux suggest :p. He suggest I put bigger values as smaller paging annoys him :p.

> should we mention and provide a link to InAWARE?

You can give me the detail, and I will put it :)

**Comment by timlinux** [comment]
A couple more papercuts from me:

- [ ] Make InaSAFE markers appear on top of OSM markers
- [ ] Make OSM markers circles based on this logo http://wiki.openstreetmap.org/wiki/File:Openstreetmapus_300x300.jpg, same size and style as InaSAFE logo.
- [ ] Change 'User management' menu to 'Account'

**Comment by lucernae** [comment]
@timlinux I think I will have to ask @MariaSolovyeva to make transparent version of http://wiki.openstreetmap.org/wiki/File:Openstreetmapus_300x300.jpg

**Comment by gubuntu** [comment]
all either done or stale or in other tickets
