### ISSUE TITLE
Find out why shake id and time doesn't match

### ISSUE THREAD

**Issue by lucernae** [inasafe/inasafe-django#84]
Example:

Shake id : 20150811225230
Time : 2015-08-12 at 05:53:08

possible bug: Timezone issues

**Comment by lucernae** [comment]
Apparently I made that the time in the table is based on the timezone of the viewer :p, sorry forgot about that. But it points at the same time. So, for example a shakemap was happen at 2015-08-18 at 21:16:23 (the timezone is Asia/Jakarta, which is GMT+07:07 in pytz), then if you saw the site from SA the time will be converted to 16:16:23 (besause SA is GMT+02), which is basically the same.

I want to have some opinion on this, @timlinux @Charlotte-Morgan which is better? Should we always uses GMT+7 time, or this current scheme. Note that, it will affect the filters, because the filters will apply to the displayed time. So in this current case the time based on the timezone. It is only a date, but in oceania for example, we can have extreme case of timezone where the dateline lies.

**Comment by Charlotte-Morgan** [comment]
Hi @lucernae 

 In other systems I am aware of (eg sentinel.ga.gov.au for fire reports) we always UTC and then you have to work it out for your self.  The queries then ask - last 6 hours, last 12 hours etc so its all relative.
![image](https://cloud.githubusercontent.com/assets/5743135/9405676/1e481e32-4824-11e5-80ea-1651a9ffb4b0.png)

I think InAWARE also uses relative time - ie reported 3 days ago etc
@samnawi - do you have any comment to add on this?

**Comment by samnawi** [comment]
Hi @Charlotte-Morgan In my experience, for Indonesia only, We use GMT+7 (Jakarta time) for the time when we develop Indonesia Disaster Watch (Pantauan Bencana).

For the time that showed in InAWARE, they use the long time from the disaster has been reported.
It's make a little bit confuse to some user that see this time to get information about time when disaster is happen. (i.e. Now is 21Aug2015 9:00 PM, the disaster is happen at 21Aug2015 7:30 PM. So the date infornation will show like this format --> reported 1 hour 30 minutes ago). 
Mr. Sutopo (Head at Center of Data, Information, and Public Relation in BNPB) has been ask the InaWARE developer to change this format to the standar data like the common. But, at that time, the developer have the reason, "It's method to accomodate the different time zone, so all of user have the same perspective that disaster was happen at a couple time ago"

That my sharing experience from me.

Thank you.

**Comment by lucernae** [comment]
@samnawi what happen for older events from, let's say, a year ago. Does the time shows: reported 1 year ago?

**Comment by samnawi** [comment]
Yes, like that @lucernae 
![selection_157](https://cloud.githubusercontent.com/assets/8871958/9570971/ca7adf2a-4fc0-11e5-807d-b4ca8ffbe3b7.png)
Like the picture in above, the eathquake was happened at 1 day 6 hours ago, or at 30 August 2015 3 am

**Comment by lucernae** [comment]
Ok, so I was thinking of the following:

- We should at least add relative time in the popup. Perhaps below date time.
- We should add some description in time column in the table, perhaps something like this:
 "Time (in timezone <insert the timezone here like Asia/Jakarta>)" Or, we can default to UTC?
- Perhaps we want to add another column in the table to show relative time? What do you think?

CC @Charlotte-Morgan @samnawi @timlinux

**Comment by samnawi** [comment]
@lucernae In my  mind, maybe we can write two format, one is like a relative time and the other is fixed time (use an agreed Time zone ). So, when the user look at this event, they can say, "The disaster is happen at 31 August 2015 3am UTC, mmm.... approximately 2 days 4 hours ago"

**Comment by timlinux** [comment]
Another option - we store the time zone for each event and show in the reporting the local time in that time zone with the time zone in brackets after. I think the grid.xml anyway provides the time zone as part of its standard metadata. I think also showing relative time is nice. So we could end up with something like:

```3 days ago (Feb 11 2015) at 08h45 (WIB)```

**Comment by gubuntu** [comment]
The time in the shakemap id is the time of creation of the shakemap and not the time of the quake. 

@lucernae has this been dealt with by now?

**Comment by gubuntu** [comment]
This issue was moved to inasafe/inasafe-realtime#123
